# Generated by Django 4.2 on 2023-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('age', models.IntegerField(default=18)),
                ('play', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True, unique=True)),
            ],
        ),
    ]
